# This file was generated by GoReleaser. DO NOT EDIT.
cask "scyllamigrate" do
  name "scyllamigrate"
  desc "A lightweight schema migration tool for ScyllaDB"
  homepage "https://github.com/heartwilltell/scyllamigrate"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scyllamigrate"

  on_macos do
    on_intel do
      url "https://github.com/heartwilltell/scyllamigrate/releases/download/v#{version}/scyllamigrate_#{version}_darwin_x86_64.tar.gz"
      sha256 "2c8b05845023486145f4880918df6c8c7991a77eb3a044a390146cc4a8fa481e"
    end
    on_arm do
      url "https://github.com/heartwilltell/scyllamigrate/releases/download/v#{version}/scyllamigrate_#{version}_darwin_arm64.tar.gz"
      sha256 "189e6cb60b4dba5430f6c99c10ea7a75a9a8d5e7cf89df449a80a119e50ba2d1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/heartwilltell/scyllamigrate/releases/download/v#{version}/scyllamigrate_#{version}_linux_x86_64.tar.gz"
      sha256 "45de7ccad7c079bfbaf24958b4c95dcb02f2720104169d5da6b398ca6effa9fe"
    end
    on_arm do
      url "https://github.com/heartwilltell/scyllamigrate/releases/download/v#{version}/scyllamigrate_#{version}_linux_arm64.tar.gz"
      sha256 "56513ee69688049ce188c99f04a2bb81cc917da798460f0afd48b6dfd6a68e44"
    end
  end

  # No zap stanza required
end
