# This file was generated by GoReleaser. DO NOT EDIT.
cask "scyllamigrate" do
  name "scyllamigrate"
  desc "A lightweight schema migration tool for ScyllaDB"
  homepage "https://github.com/heartwilltell/scyllamigrate"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scyllamigrate"

  on_macos do
    on_intel do
      url "https://github.com/heartwilltell/scyllamigrate/releases/download/v#{version}/scyllamigrate_#{version}_darwin_x86_64.tar.gz"
      sha256 "79d7d4fa7f7797a1b4385abf16e0afc292d24d108bfe35720f458227ad5619ca"
    end
    on_arm do
      url "https://github.com/heartwilltell/scyllamigrate/releases/download/v#{version}/scyllamigrate_#{version}_darwin_arm64.tar.gz"
      sha256 "a89b1d102a1ead52eedabf28cabcf379911e6b17c1b4d493c95e0cde45697534"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/heartwilltell/scyllamigrate/releases/download/v#{version}/scyllamigrate_#{version}_linux_x86_64.tar.gz"
      sha256 "6c713fbe027c195f5846fdb762aebe668a17bed0e19afe1bc79bb41a6d76a68a"
    end
    on_arm do
      url "https://github.com/heartwilltell/scyllamigrate/releases/download/v#{version}/scyllamigrate_#{version}_linux_arm64.tar.gz"
      sha256 "853c7410ff754dd0f1b30ed77050fb747e8cda1030f55d2dc368caff1b622e6d"
    end
  end

  # No zap stanza required
end
